spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skiplocked
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
